version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs_container
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - db_data:/var/lib/mysql

  apache:
    image: httpd:latest
    container_name: apache_container
    ports:
      - "80:80"
    volumes:
      - ./public-html:/usr/local/apache2/htdocs/

volumes:
  db_data: